insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Agumon', '2020-02-03', 10.23, True, 0);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Gabumon', '2018-11-15', 8, True,2);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Pikachu', '2021-01-07', 15.04, False,1);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Devimon', '2017-05-12', 11, True,5);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Charmanders', '2020-02-20', 11, False,0);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Plantmon', '2021-11-15', 5.7, True,2);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Squirtle', '1993-04-15',12.13, False,3);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Angemon', '2005-12-06',45, True,1);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Borman', '2005-06-07',20.4, True,7);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Blossom', '1998-10-13','17', True,3);
insert into animals (name, date_of_birth, weight_kg, neutered, escape_attemps) values('Ditto', '2022-05-14','22', True,4);
